### ISSUE TITLE
Notification on RuneLite start in bright red text

### ISSUE THREAD

**Issue by KempQ11** [BarelyFunctionalCode/animation-transmog#16]
There is a jarring notification that appears on RuneLite start, "To enable new functionality, please go to the plugin settings and check 'Enable Multiplayer' on."

I'm not interested in that multi-player feature, so I'd prefer to find a way to disable this notification that doesn't give my IP unnecessarily.  Could there please be an opt-in notification of, "Notify if Multiplayer is disabled"?

**Comment by BarelyFunctionalCode** [comment]
I have made a PR to the plugin-hub for this update. After that PR has been merged, the chat message will no longer show up.

https://github.com/runelite/plugin-hub/pull/5777

**Comment by KempQ11** [comment]
Thank you so much! I love this plugin a whole lot, it adds so much production quality to B-Roll for videos.

**Comment by BarelyFunctionalCode** [comment]
I have an idea for a new plugin if I ever get back into working on OSRS plugins in the ever growing list of my other hobby projects. 

Essentially it would be extracting the feature that you guys use in this plugin and making a much more polished version.

Kinda like the sidebar of Runelite would look like a video editor timeline and you can drag animations and effects in the timeline then play them all in a chain properly spaced out to achieve some automated b-roll or other cinematic scenes for YouTube videos.

If you're interested in something like that, maybe email me or message on Discord with how you think something like that would work well for a content creator. I haven't really fleshed out the idea, but it's something in my wheelhouse that I could get going.

**Comment by BarelyFunctionalCode** [comment]
This update has been pushed to the game.
