### ISSUE TITLE
Colosseum doom death animation as death animation

### ISSUE THREAD

**Issue by Jdifo** [BarelyFunctionalCode/animation-transmog#17]
Dying from the doom invocation in the colosseum has a cool animation that turns you into a green skeleton as you die. Could this be added as a death animation transmog?

**Comment by BarelyFunctionalCode** [comment]
Yeah that's a good idea, I'll just need to dig around to find the animation ID for it and then I can add it in.

**Comment by BarelyFunctionalCode** [comment]
After looking through all the latest animations and GFXs, I've come up with 3 new death animations for the plugin, including the doom death one you mentioned.

Melt:

[melt](https://github.com/BarelyFunctionalCode/animation-transmog/assets/7527934/997289f1-0d66-4ed9-97b3-9811e4511682)

Blaze:

[blaze](https://github.com/BarelyFunctionalCode/animation-transmog/assets/7527934/d57ab5a4-a07b-4ba0-9d22-bcc99e0d9b09)

Vaporize:

[vaporize](https://github.com/BarelyFunctionalCode/animation-transmog/assets/7527934/02f856f4-c358-4e81-ad49-4edabc21bf74)

If this is what you were looking for I can go ahead and submit this update to the plugin-hub.
